Connect Dashboard Screen to Firebase Database
arygm/QuickFix pull request #199
Opened 2024-12-05 03:49 UTC by JitterKiller

### Description

This PR connects the Dashboard screen to the Firebase database, enabling it to display real-time data for QuickFixes and Messages. The following changes have been made:

- **Firebase Integration**: Integrated Firebase Firestore to fetch real-time data for QuickFixes and Messages.
- **Dashboard Screen**: Updated `DashboardScreen` to display actual QuickFixes from the database.
- **Messages Widget**: Modified `MessagesWidget` to show real messages retrieved from Firestore.
- **ViewModel and Repository Updates**: Implemented necessary changes in ViewModel and Repository to support data fetching.
- **Firestore Deserialization**: Added no-argument constructors to data classes for Firestore deserialization.
- **Timestamp Formatting**: Ensured proper formatting of timestamps in `MessageItem`.

### Changes

- **DashboardScreen.kt**: Connected to Firebase and updated to display real-time QuickFixes and Messages.
- **ChatRepositoryFirestore.kt**: Added methods to fetch and display real-time messages.
- **QuickFixRepositoryFirestore.kt**: Added methods to fetch and display real-time QuickFixes.
- **Data Classes**: Added no-argument constructors for Firestore deserialization.
- **MessageItem.kt**: Updated timestamp formatting logic.

### Testing

- **Unit Tests**: Added unit tests to verify the correct display of QuickFix filter buttons and widgets.
- **Integration Tests**: Verified the integration with Firebase Firestore and the correct display of real-time data.

### Screenshots
![Capture d’écran 2024-12-05 à 04 47 38](https://github.com/user-attachments/assets/45695c8b-4219-4170-a7fc-3a835fbafe86)
![Capture d’écran 2024-12-05 à 04 47 45](https://github.com/user-attachments/assets/f53c6d50-b4ac-4932-b574-5204df529d37)

2024-12-09 06:58 UTC, ramshty requested changes
Look with Mehdi about the use of loggedInAccount to change it and use instead preferenceViewModel that makes the use of caching.

2024-12-09 06:58 UTC, ramshty commented on app/src/main/java/com/arygm/quickfix/ui/dashboard/Dashboard.kt
Excellent move to modularize your code by introducing the Status enum! This aligns perfectly with the architecture I envisioned while planning the backend implementation. It not only makes the code cleaner but also enhances maintainability. Fantastic enhancement!

2024-12-09 06:58 UTC, ramshty commented on app/src/main/java/com/arygm/quickfix/ui/dashboard/MessagesWidget.kt
perfect link to the backend. Nice job !!

2024-12-09 06:58 UTC, ramshty commented on app/src/main/java/com/arygm/quickfix/ui/home/MessagesScreen.kt
you will have to adapt this file using preference view model since loggedInAccount is deprecated. You need to ask Mehdi of how doing these changes. I let you get in touch with him.

2024-12-15 12:46 UTC, closed without merging

2024-12-15 12:48 UTC, JitterKiller commented
This PR won't be merged because it took too long to get the code from other team members, making the code obsolete.
A new PR will be opened for the DashBoard screen (#242)