feature: added working hours
arygm/QuickFix pull request #252
Opened 2024-12-17 15:56 UTC by ramshty

- Added the possibility for the worker to select its working hours

2024-12-17 19:34 UTC, daferya requested changes
You've written excellent tests that cover all the important cases and implemented exactly what we discussed during the meeting. Just be careful with absolute values and consider replacing them with relative ones.

2024-12-17 19:34 UTC, daferya commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/TimeDropDownMenu.kt
> +        Box(modifier = Modifier.size(width = 80.dp * widthRatio.value, height = 300.dp)) {
try to use height ratio instead of absolute values

2024-12-17 19:34 UTC, daferya commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
> +                        .padding(top = 20.dp, end = 12.dp))
try to not use absolut value

2024-12-19 23:48 UTC, JitterKiller approved these changes
Overall great PR!

Adding time slots for working hours is a good feature to have.
Just make sure to avoir using absolute values especially values like `300.dp` 😅

Other that LGTM

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/UpgradeToWorkerScreen.kt
> +            "workerProfile: ${locationWorker.value.name} ${fieldOfWork.value} ${description.value} ${price.doubleValue} ${displayName.value} ${includedServices.value} ${addOnServices.value} ${tags.va
You can remove theses logs here 😄

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/UpgradeToWorkerScreen.kt
> +                    if (workingHours.value.first == null || workingHours.value.second == null)
Checking if one of the value if null is good 👍🏼

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/personal/PersonalInfoScreen.kt
> +            onClickAction = { navigationActions.goBack() },
Nice 👍🏼

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
> +                        .padding(top = 20.dp, end = 12.dp))
Yup, absolute values here, could be avoided but it's ok

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
> +                              onClickAction = { navigationActions.goBack() },
👍🏼

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
> +    durationMillis: Int = 1 // Total animation duration
Maybe a bit too fast?

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/TimeDropDownMenu.kt
> +        Box(modifier = Modifier.size(width = 80.dp * widthRatio.value, height = 300.dp)) {
Again here, just add heightRatio.value

2024-12-19 23:48 UTC, JitterKiller commented on app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/TimeDropDownMenu.kt
> +                          .padding(horizontal = 8.dp)
Same here, use widthRatio.value

2024-12-20 00:24 UTC, merged